on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  test-secrets-access:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${SECRET}" = "BOOP" ]; then
            echo >&2 "Secrets are working!"
          else
            echo >&2 "Secrets doesn't work :("
            exit 1
          fi
        env:
          SECRET: ${{ secrets.TEST }}
